app:
  security:
    user-info-uri: http://auth-service:5000/uaa/users/current
    # used by CustomUserInfoOpaqueTokenIntrospector

spring:
  security:
    oauth2:
      client:
        registration:
          my-client:
            authorization-grant-type: client_credentials
            client-id: account-service
            client-secret: ${ACCOUNT_SERVICE_PASSWORD}
            scope: server
        provider:
          my-auth:
            token-uri: http://auth-service:5000/uaa/oauth/token

  data:
    mongodb:
      host: account-service-db
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27017

  cloud:
    openfeign:
      oauth2:
        enabled: true
        clientRegistrationId: my-client
      # If you want Feign methods wrapped with circuit breakers, uncomment:
      # circuitbreaker:
      #   enabled: true

server:
  servlet:
    context-path: /accounts
  port: 6000

resilience4j:
  timelimiter:
    configs:
      default:
        timeoutDuration: 10s
        cancelRunningFuture: true






#security:
#  oauth2:
#    client:
#      clientId: account-service
#      clientSecret: ${ACCOUNT_SERVICE_PASSWORD}
#      accessTokenUri: http://auth-service:5000/uaa/oauth/token
#      grant-type: client_credentials
#      scope: server
#    resource:
#      user-info-uri: http://auth-service:5000/uaa/users/current
#
#spring:
#  data:
#    mongodb:
#      host: account-mongodb
#      username: user
#      password: ${MONGODB_PASSWORD}
#      database: piggymetrics
#      port: 27017
#
#server:
#  servlet:
#    context-path: /accounts
#  port: 6000
#
#feign:
#  hystrix:
#    enabled: true
