app:
  security:
    user-info-uri: http://auth-service:5000/uaa/users/current
    # used by CustomUserInfoOpaqueTokenIntrospector

logging:
  level:
    org.springframework.security: INFO

# remove Hystrix, replace with resilience4j
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 10000

resilience4j:
  timelimiter:
    configs:
      default:
        timeoutDuration: 10s
        cancelRunningFuture: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/

#security:
#  oauth2:
#    resource:
#      user-info-uri: http://auth-service:5000/uaa/users/current

spring:
  rabbitmq:
    host: rabbitmq



#  security:
#    user-info-uri: http://auth-service:5000/uaa/users/current