# security:
#   oauth2:
#     client:
#       clientId: statistics-service
#       clientSecret: ${STATISTICS_SERVICE_PASSWORD}
#       accessTokenUri: http://auth-service:5000/uaa/oauth/token
#       grant-type: client_credentials
#       scope: server

# spring:
#   data:
#     mongodb:
#       host: statistics-mongodb
#       username: user
#       password: ${MONGODB_PASSWORD}
#       database: piggymetrics
#       port: 27017

spring:
  security:
    oauth2:
      client:
        registration:
          my-client:
            authorization-grant-type: client_credentials
            client-id: statistics-service
            client-secret: ${STATISTICS_SERVICE_PASSWORD}
            scope: server
            provider: my-auth
        provider:
          my-auth:
            token-uri: http://auth-service:5000/uaa/oauth/token
  data:
    mongodb:
      uri: mongodb://app_user:${MONGODB_PASSWORD}@statistics-service-db:27017/statistics?authSource=statistics

server:
  servlet:
    context-path: /statistics
  port: 7000

rates:
  url: https://api.exchangeratesapi.io
